export const featuredProducts = [
  {
    id: 'mock-notebook',
    name: 'Sổ tay học kỳ A5',
    category_name: 'Văn phòng phẩm',
    price: 45000,
    stock_quantity: 120,
    image_url: '',
  },
  {
    id: 'mock-headphone',
    name: 'Tai nghe học online Lite',
    category_name: 'Thiết bị học tập',
    price: 299000,
    stock_quantity: 34,
    image_url: '',
  },
  {
    id: 'mock-bottle',
    name: 'Bình nước giữ nhiệt 500ml',
    category_name: 'Đời sống sinh viên',
    price: 189000,
    stock_quantity: 58,
    image_url: '',
  },
  {
    id: 'mock-keyboard',
    name: 'Bàn phím không dây Compact',
    category_name: 'Phụ kiện máy tính',
    price: 420000,
    stock_quantity: 17,
    image_url: '',
  },
  {
    id: 'mock-lamp',
    name: 'Đèn bàn LED chống mỏi mắt',
    category_name: 'Góc học tập',
    price: 260000,
    stock_quantity: 45,
    image_url: '',
  },
  {
    id: 'mock-backpack',
    name: 'Balo laptop 15 inch',
    category_name: 'Phụ kiện',
    price: 520000,
    stock_quantity: 23,
    image_url: '',
  },
];
